### PR TITLE
Add possibility for storing config options in app.config of current project

### PR DESCRIPTION
**Pull request by grechman2**
We faced with a problem that our test project is configure via app.config and it would be great to have possibility to configure reportportal-net-agent via app.config, as we run our tests on different envs, we use transformation to change app.config for different envs.

### CODE REVIEW

**Comment by grechman2** [comment]
@nvborisenko , Nikolay, thanks for reply! Please take a look at readme file update. Could you please advice on one more thing? Need to pass launch name as a parameter to reportportal, is it possible to pass parameters or it is not implemented yet? The only way for now, that I am aware of id is hardcoded value in config file. But we have many test jobs in CI (teamcity) and it would be a mess to store all those test runs under one name. Thanks!

**Comment by nvborisenko** [comment]
You can find an example how to customize reporting in realtime: https://github.com/reportportal/example-net-specflow/blob/master/src/Example.SpecFlow/Hooks/Hooks1.cs

**Comment by grechman2** [comment]
@nvborisenko Nikolay, please, advice, what should I change in that pull request for it to be approved? Thanks!

**Comment by nvborisenko** [comment]
@grechman2 your changes are in ReportPortal.SpecFlow.1.2.0-beta-4

**Comment by grechman2** [comment]
thanks!

**Pull request merged**
