### PR TITLE
Fix handling of BeforeFeature

### LINKED ISSUE #75: Withing RP integrated scenarios are executed even if [BeforeFeature] hook fails

### PR DESCRIPTION
**Pull request by maaex**
This fixes #75 

Currently, when exceptions occur in BeforeFeature and BeforeTestRun, they are swallowed by `SafeBindingInvoker` and are not displayed anywhere to the user. The tests continue to run as usual (see passing `ThisScenarioShouldFailBecauseOfFeatureFailsBefore` and all passing tests when uncommenting the `throw` statement in the `BeforeTestRun` hook in `ReportPortal.SpecFlowPlugin.IntegrationTests.Hooks`.

This PR makes it so failures in BeforeFeature and BeforeTestRun causes test failures. In addition, any exception thrown in BeforeFeature can be seen in the error message in RP for all scenarios in that feature. Exceptions in BeforeTestRun will cause all scenarios to have the "Skipped" status.

### CODE REVIEW

**Comment by nvborisenko** [comment]
Thank you @maaex , this is major issue we wanted to fix.

Is it possible to fail scenarios if BeforeTestRun hook fails?

**Comment by maaex** [comment]
> Thank you @maaex , this is major issue we wanted to fix.
> 
> Is it possible to fail scenarios if BeforeTestRun hook fails?

There is no FeatureContext available at that point so the solution would have to be different.
I noticed that there is a TestThreadContext with a TestError property. I could probably use that in the same way that I'm using FeatureContext for BeforeFeature, but I have no idea what other effects (if any) that would have. What do you think?

**Comment by nvborisenko** [comment]
In general applying SafeBindingInvoker approach is kind of workaround, we can do everything here what we need... despite the fact that user may register his own SafeBindingInvoker. We don't care.

The right solution would be https://github.com/reportportal/agent-net-specflow/issues/49 but it is not ready yet, at least not ready for us.

**Comment by maaex** [comment]
There seems to be some weird race conditions going on with the TestThreadContext. When I'm handling it in the same way as the FeatureContext in my PR, the tests pass when running them normally but fail when I debug them.

If possible, I would prefer if we could merge this PR first and look into improvements later?

**Comment by nvborisenko** [comment]
@maaex Sorry for long absence, your fix is released as **v4.6.2**. Thank you for contribution.

**Pull request merged**
